[package]
name = "half-a-game"
version = "0.1.0"
authors = ["Caspar Krieger <caspar@asparck.com>"]

[dependencies]
piston_window = "0.14.0"
find_folder = "*"
piston-ai_behavior = "*"
piston2d-sprite = "*"
gfx_device_gl = "*"
uuid = "*"
